run_tests:
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  image: docker:28.3.3
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t nurjamia/nurown:python2 .
    - docker push nurjamia/nurown:python2